### ISSUE TITLE
PEP-8 명세도입 Flake8

### ISSUE THREAD

**Issue by gomjellie** [iipeace/guider#104]
pep-8 에 관한 설명이 정리된 블로그입니다.

https://spoqa.github.io/2012/08/03/about-python-coding-convention.html

Flake 8 에 대한 설명이 잘 정리된 블로그입니다.

https://tech.songyunseop.com/post/2017/05/lint-with-flake8/

파이썬 코드 컨벤션 체크하는 툴 인데, guider 전체에 한번에 적용하기에는 기존의 guider 코드가 너무 많아서 작은 코드들 부터 도입하는게 어떨까요? ci에 붙일수도 있어요

**Comment by iipeace** [comment]
좋은 내용이네요!
저도 검토해보고 회신할게요 :)

**Comment by gomjellie** [comment]
guider 디렉토리에 있는 코어 코드는 너무 방대해서 안될것같고 비교적 최근에 새로 만들고 있는 agent 디렉토리 만 적용하는것이 현실적으로 좋을것 같습니다!

**Comment by iipeace** [comment]
동의합니다!
코딩 컨벤션도 습관이니 이제 flask 코드부터는 가능한 통일하여 시작하시지요 :)
