### ISSUE TITLE
대시보드 그래프 구현

### ISSUE THREAD

**Issue by MoonHyuk** [iipeace/guider#116]
우선은 DB고려 없이 대시보드 진입 이후의 데이터만 보여지도록 구현

1. CPU 정보 (꺾은선그래프)
{ 'CPU': {'total'} }
Label로 'nrCore' 값 추가
단위는 %

2. Memory 정보 (꺾은선그래프)
{ 'mem': {'available'} }
Label로 'total' 값 추가
단위는 MB

3. Storage 정보 (꺾는선그래프)
{ 'storage': { 'total': { 'free' } } }
Label로 { 'total': { 'total' } } } 값 추가
단위는 MB

4. Network 정보 (꺾는선그래프)
{ 'net': { 'inbound', 'outbound' } }
단위는 Byte

**Comment by MoonHyuk** [comment]
작업 예정

**Comment by MoonHyuk** [comment]
related #66

**Comment by iipeace** [comment]
@MoonHyuk,

제안하신 영역그래프 데이터도 포함하여 다시 공유드립니다.

1. CPU 정보 (영역그래프)
key = json_pipe['cpu']
'total' = 'kernel' + 'user' + 'irq'
Label로 'nrCore' 값 추가
단위는 %

2. Memory 정보 (영역그래프)
key = json_pipe['mem']
'total' = 'kernel' + 'cache' + 'free' + 'anon'
Label로 'total' 값 추가
단위는 MB

3. Storage 정보 (영역그래프)
key = json_pipe['storage']['total']
'total' = 'free' + 'usage'
Label로  'total'  값 추가
단위는 MB

4. Network 정보 (선그래프)
key = json_pipe['net']
'inbound', 'outbound'
단위는 Byte


Storage 정보와 Network 정보 관련 데이터를 Guider로부터 제대로 받아오려면,
flask에서 아래의 내용을 바꿔야 합니다. (@yangsso)
1. Guider 명령어 수정
`"Guider top -J -e d, n"`
2. Vue로 전달하는 데이터 추가
`msg['storage_pipe'] = json.dumps(json_pipe["storage"])`
`msg['net_pipe'] = json.dumps(json_pipe["net"])`

**Comment by yangsso** [comment]
@iipeace  태그주신 부분은 이슈 하나 찢어서 진행할게요~

**Comment by iipeace** [comment]
@yangsso,
네, 별도 이슈로 진행해주셔요 :)

**Comment by yangsso** [comment]
@MoonHyuk 님 참고요

{'timestamp': 1382009.08, 'cpu': {'total': 0, 'nrCore': 4}, 'memory': {'total': 7978}, 'storage': {'total': 22795}, 'network': {'inbound': 52, 'outbound': 52}}
