### ISSUE TITLE
json data 데이터 채집 시 timestamp 오류

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#117]
@iipeace guider 에서 해당 데이터가 채집된 timestamp를 넘겨주는게 제일 정확 할 것 같은데 
우선은 가이더 response 온 시간에 timestamp 넣게 할건데 
이거 한번 확인 부탁드려요

**Comment by iipeace** [comment]
@yangsso, @MoonHyuk,

현재 Guider에서는 JSON 형식의 response 내부에서 'timestamp' 값을 넘겨주고 있습니다.
'timestamp'는 target의 POWER ON 시점부터 소요된 시간(second)이며,
매 초마다 갱신되고 있는 것을 확인하였습니다.

그래프부터 모든 데이터들의 시간은 이 'timestamp' 값을 기준으로 사용되어져야 하는데,
현재 flask 코드에서는 이 값을 사용하고 있지 않네요.
말씀드린 값은 json_pipe['timestamp']입니다.

**Comment by yangsso** [comment]
@iipeace 옙 그럼 그거 맞춰서 작업해놓을게요~
