### ISSUE TITLE
sidebar 페이지 변경 시 ip 데이터 초기화 되는 버그

### ISSUE THREAD

**Issue by KangWooJin** [iipeace/guider#138]

**Comment by Agrajak** [comment]
vuex로 관리하시나요?

**Comment by Agrajak** [comment]
vuex로 하시면 https://www.npmjs.com/package/vuex-persistedstate 이거 적용시키면 평화님이 말씀하신 거도 해결될 것 같아요

**Comment by KangWooJin** [comment]
@Agrajak Vuex를 사용할 예정인데, session, cookie에 관리를 해야 하는지 결정이 필요하겠네요 @iipeace 님 데이터를 리셋하는 시점이 페이지를 새로고침시, 브라우저 종료 시, 특정 시간 경과 후 등 어느 시점이 좋은지 코멘트 부탁드립니다.

**Comment by iipeace** [comment]
@KangWooJin,
브라우저 종료 시로 설정하는게 좋을 것 같습니다.

**Comment by KangWooJin** [comment]
vue route로 페이지 전환간에 topNavBar 데이터 초기화 되는 부분은 해결하였으나 차후에 vuex에 적용이 필요
