### ISSUE TITLE
command page의 hot command

### ISSUE THREAD

**Issue by iipeace** [iipeace/guider#141]
하기 command에 대해 hot command 등록하고,
각 hot command 클릭하면 check box로 option 체크 및 입력할 수 있으면 좋겠습니다.

[ command ]
1. top
2. disktop
3. nettop
4. filetop
5. systop
6. usertop

[ option ]
guider.py COMMAND -h 입력하면,
각 command 별 option들이 나오는데,
해당 옵션들을 checkbox로 표시하고,
입력이 필요한 옵션들 옆에는 inputbox도 있으면 좋겠습니다.

@KangWooJin

**Comment by KangWooJin** [comment]
#152 작업 완료

**Comment by KangWooJin** [comment]
@iipeace Please close this issue
