### ISSUE TITLE
manage.py 실행 시 command line에서 IP 및 PORT 입력 방법

### ISSUE THREAD

**Issue by iipeace** [iipeace/guider#142]
@yangsso,
# python manage.py run
혹시 지금 위의 명령어를 command line에서 입력 시 IP와 PORT 정보도 넘길 수 있을까요?

**Comment by KangWooJin** [comment]
@iipeace 님 해당 방식으로 하면은 나중에 guider (N) : flask(1) 구조에 문제가 있지 않을까요?

**Comment by iipeace** [comment]
@KangWooJin
여기에서 사용하는 IP와 PORT는 Guider아 아닌 flask의 주소입니다 :)
