### ISSUE TITLE
error when executing "pip install -r requirements.txt" command

### ISSUE THREAD

**Issue by iipeace** [iipeace/guider#145]
제 기기에서 아래와 같이 에러가 발생하는데,
more-itertools==7.2.0에 대한 버전이 너무 높진 않을까요?

iipeace@~/work/guider/agent$ sudo pip2 install -r requirements.txt 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/home/iipeace/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/iipeace/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: aniso8601==8.0.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (8.0.0)
Requirement already satisfied: atomicwrites==1.3.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (1.3.0)
Collecting attrs==19.2.0
  Downloading https://files.pythonhosted.org/packages/6b/e8/2ecaf86b128a34e225807f03b22664302937ab826bd3b7eccab6754d29ea/attrs-19.2.0-py2.py3-none-any.whl (40kB)
     |████████████████████████████████| 40kB 141kB/s 
Collecting bson==0.5.8
  Downloading https://files.pythonhosted.org/packages/b9/42/e823b5f13515e3af308fb6efcacff456fc59078ec0e9ac426e842d66c9cb/bson-0.5.8.tar.gz
Requirement already satisfied: Click==7.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (7.0)
Requirement already satisfied: Flask==1.1.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6)) (1.1.1)
Collecting Flask-Cors==3.0.8
  Downloading https://files.pythonhosted.org/packages/78/38/e68b11daa5d613e3a91e4bf3da76c94ac9ee0d9cd515af9c1ab80d36f709/Flask_Cors-3.0.8-py2.py3-none-any.whl
Requirement already satisfied: flask-mongoengine==0.9.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8)) (0.9.5)
Collecting Flask-PyMongo==2.3.0
  Downloading https://files.pythonhosted.org/packages/67/b8/0322016b9ce09a64fba9018211e7c35fd51380527ffd9ea248744f389239/Flask_PyMongo-2.3.0-py2.py3-none-any.whl
Requirement already satisfied: Flask-RESTful==0.3.7 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10)) (0.3.7)
Requirement already satisfied: Flask-Script==2.0.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11)) (2.0.6)
Requirement already satisfied: Flask-SocketIO==4.2.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12)) (4.2.1)
Requirement already satisfied: Flask-WTF==0.14.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13)) (0.14.2)
Requirement already satisfied: importlib-metadata==0.23 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14)) (0.23)
Requirement already satisfied: itsdangerous==1.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15)) (1.1.0)
Requirement already satisfied: Jinja2==2.10.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16)) (2.10.1)
Requirement already satisfied: MarkupSafe==1.1.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17)) (1.1.1)
Requirement already satisfied: mongoengine==0.18.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 18)) (0.18.2)
ERROR: Could not find a version that satisfies the requirement more-itertools==7.2.0 (from -r requirements.txt (line 19)) (from versions: 1.0, 1.1, 2.0, 2.1, 2.2, 2.3, 2.4, 2.4.1, 2.5.0, 2.6.0, 3.0.0, 3.1.0, 3.2.0, 4.0.0, 4.0.1, 4.1.0, 4.2.0, 4.3.0, 5.0.0)
ERROR: No matching distribution found for more-itertools==7.2.0 (from -r requirements.txt (line 19))

**Comment by Agrajak** [comment]
저가 예전에 requirements.txt를 pip3에서 freeze해서... pip3 install로 설치하시면 해결 될 거에요

**Comment by iipeace** [comment]
@Agrajak,
flask는 python3으로만 지원해야겠네요 :)

**Comment by GabsRTX** [comment]
you are using pip2 and ERROR: Could not find a version that satisfies the requirement more-itertools==7.2.0 because https://pypi.org/project/more-itertools/ says Requires: Python >=3.4

**Comment by yoonje** [comment]
need to close because guider dont have requirements.txt now.
