### ISSUE TITLE
Changing some field names

### ISSUE THREAD

**Issue by honggyukim** [iipeace/guider#18]
I think it'd be better to change some field names. Currently, it seems that `ID` shows pid(process id) and `Pid` means ppid(parent process id) but it looks confusing to understand at first.
```
    ...
==============================================================================
    Process      ( ID  / Pid / Nr / Pri)| CPU(Usr/Ker/Dly)|  ...
------------------------------------------------------------------------------
    ...
```
I think those fields can be change as follows:
- `ID` to `pid`
- `Pid` to `ppid`

What do you think?

**Comment by iipeace** [comment]
I think you're right.
the reason why I wrote it is that there are two modes.
- process mode (default)
- thread mode (with -e t option)

anyway, I changed menu to get rid of confusion :)
- 090306f905892af5efdb55af5632ba58b1edf3f0

**Comment by honggyukim** [comment]
Thanks!
