### ISSUE TITLE
Require interface to ask and response to check health for Guider server

### ISSUE THREAD

**Issue by iipeace** [iipeace/guider#190]

**Comment by KangWooJin** [comment]
flask socket io에서 PING 관련 설정이 있어서 해당 부분으로 사용가능 한지 확인해보겠습니다.
https://flask-socketio.readthedocs.io/en/latest/

**Comment by iipeace** [comment]
Guider에서도 NetworkManager.requestPing() method를 추가하였습니다.
return이 True일 경우에만 alive로 보시면 됩니다.

@yangsso님 통해서 반영해야 하나요?

**Comment by KangWooJin** [comment]
@iipeace I will check it.

**Comment by yoonje** [comment]
need to close
