### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by iipeace** [iipeace/guider#204]
1 serialize-javascript vulnerability found in …/front-vue/yarn.lock 14 hours ago

Remediation

Upgrade serialize-javascript to version 2.1.1 or later. For example:

serialize-javascript@^2.1.1: version "2.1.1"

Always verify the validity and compatibility of suggestions with your codebase.

**Comment by ainneo** [comment]
I updated in the terminal, the file has updated in the json file, but not in the yarn lock file... does anyone know how I can update this in the yarn lock file?

**Comment by yoonje** [comment]
need to close
