### ISSUE TITLE
향후 웹 아키텍처 방향에 관한 정리

### ISSUE THREAD

**Issue by yoonje** [iipeace/guider#213]
### Web Socket + Non DB(Current)
![DBless](https://user-images.githubusercontent.com/38535571/77916985-e17e3780-72d4-11ea-88d8-0beb7e5ed82e.png)

- 시나리오
1. 브라우저를 통해 웹 서버 접속
2. 브라우저에서 타겟 가이더와 수행할 커맨드를 날림
3. 브라우저와 django 서버간의 web socket 연결 이후 django 서버와 guider간의 TCP socket 연결
4. 커맨드에 해당하는 데이터를 guider는 socket를 통해 django 서버로 전송하고 django 서버는 이를 브라우저로 web socket을 통해 전달하여 시각화
5. 브라우저 종료 전까지 데이터를 전송 받아 지속적으로 시각화
6. 브라우저가 꺼지면 web socket 연결 종료 이후 TCP socket 종료
- 장점
1. 가이더 서버에 TCP 소켓 접속과 종료가 복잡하지 않음
2. DB 관리 이슈가 없음
- 단점
1. N개의 브라우저에서 하나의 가이더에 대해 결과 데이터를 얻을 경우 N개의 TCP 연결과 N개의 JSON 데이터 통신 통로가 생성(N:N)되어 가이더 서버에 영향
2. 데이터를 저장하지 않기 때문에 브라우저가 꺼지면 데이터 휘발
3. 브라우저를 오래 켜둘 경우 데이터가 메모리 상에 누적

### API + DB
![DB](https://user-images.githubusercontent.com/38535571/77917008-e8a54580-72d4-11ea-9c5c-177804a10f1d.png)

- 시나리오
1. 브라우저를 통해 웹 서버 접속
2. 브라우저에서 가이더와 웹서버의 TCP 연결이 되어 있지 않으면 버튼 등을 통해 연결 요청
3. 브라우저에서 타겟 가이더와 수행할 커맨드 정보를 API를 통해 호출
4. API 서버는 요청에 맞춰 DB에 접근하여 해당 가이더의 결과 데이터를 얻음
5. API를 주기적으로 호출하여 데이터를 전송 받아 지속적으로 시각화
6. 브라우저에서 버튼 등을 통해 가이더와 웹서버의 TCP 연결 해제 요청(선택)
- 장점
1. N개의 브라우저에서 하나의 가이더에 대한 결과 데이터를 얻을 경우에도 1개의 TCP 연결과 1개의 JSON 데이터 통로가 생성(N:1)되어 가이더 서버에 영향 최소
2. Grafana를 DB에 붙여 시각화 가능
3. 데이터가 저장되어 이후 재사용 가능
4. 웹 브라우저와 가이더 간의 의존성이 사라져서 독립적으로 운영 가능(웹 브라우저가 없어도 가이더의 데이터 수신 가능)
- 단점
1. DB 설치 및 DB에 적재된 데이터에 대한 관리가 필요 
2. 가이더 서버에 TCP 소켓 접속과 종료 시점을 별도 정의가 필요
3. 가이더 서버와 웹 서버 간의 TCP 연결 상태를 사용자에게 나타내는 별도 기능 필요

**Comment by yangsso** [comment]
@yoonje 님 고생하셨어요~~ 추가 의견드립니다.
DB 사용하지 않는 방향으로 진행하는 경우 추가로 고려해야 할 부분은 아래와 같을 거 같아요
1.  임베디드 서버의 멀티 커넥션의 부담을 줄여줘야 한다 
2. 양방향의 health 체크에 대한 구현에 대해서 다양한 시나리오로 보완이 필요하다. 

DB 를 사용하는 방향으로 진행하는 경우 추가 고려사항은 아래와 같을 것 같구요
1. 1초마다 data 가 쌓이기 때문에 50byte 씩만 쌓인다고 해도 그 양이 어마어마 하다 (그야말로 대용량) 
데일리로 데이터를 쓰고 버린다던지.... 모든 데이터를 가져갈거면 멀티서버에 분산이 필요한 정도의 데이터 양이다 
2. db 사용의 경우 데이터 삭제 job 을 추가 개발 해야한다.  (이 부분이 사용자에게 다른 병목으로 다가올 수 도 있다고 보임)

결론적으로 강제로 DB 를 사용하게 된다면 오픈소스인 가이더를 유연하게 사용하지 못하게 막는 방향이 될 수 있는걸로 보입니다. 
정리해주신거에 추가로 제가 제시 할 수 있는 방향은 아래 세가지 정도가 생각 되요
1. db 를 써서 데이터를 적재 하여 api 통신을 할 건지, 그냥 socket 통신을 할지에 관해서는  옵션 선택 가능하도록 한다.
2. in memory db 인 redis 사용을 고려한다 ( 데이터 생명주기 세팅)
3. 가이더가 맺을 수 있는 최대의 tcp max connection 개수를 제한한다.

@iipeace 님 관련해서 코멘트 부탁드려요

**Comment by yoonje** [comment]
@iipeace 
추가적으로 가이더의 성능 분석 결과 데이터 중 저장이 필요한 데이터가 있는지와 실제 환경에서 가이더를 사용하는 방식에 대해서 코멘트 해주시면 도움이 될 것 같습니다. 후자에 대해서 좀 더 말씀드리면 짧게 가이더를 구동하고 데이터를 확인하는 방식으로 사용하시는지 모니터링처럼 오랜 시간 사용하시는지 궁금합니다.

**Comment by iipeace** [comment]
@yoonje, @yangsso,

실사용에서 고려해야 할 부분은 아래와 같습니다.
1. 보통은 접속한 시점부터 Target의 성능 현황을 시각화하여 보여주기 시작
2. 특수한 경우(메모리 누수 분석, 비정상적인 CPU 사용 등)를 감지하기 위해 장시간 모니터링

저장할 데이터는 시각화에 필요한 JSON 형식의 대부분 정보가 모두 필요하며,
장시간 모니터링과 서버 부하를 위해 Guider가 기본 1초 단위가 아닌  3초 혹은 5초 이상의 주기로 성능 정보를 리포트 하도록 설정하면 데이터의 양은 어느정도 조절 가능할 것입니다.

개인적으로는 대량의 데이터를 저장하고 복원하여 시각화 하기에 DB가 필요하면서도,
가능하면 web 버전을 설치하고 사용하는 Host 입장에서 최대한 쉽고 가볍게 쓸 수 있었으면 좋겠는데,
적당한 구조가 있을까요? :)

**Comment by yangsso** [comment]
@iipeace @yoonje 님 
1. 타겟의 실시간 시각화 데이터의 경우에는 저장이 필요없어 보이기 때문에 websocket  으로만으로 충분 할 것 같습니다.
2.  우선 대용량 데이터를 다루는것은 꽤 힘든일이기 때문에.. 만약 장시간 모니터링이 필요한 경우에 계속해서 시각화해서 모니터링이 필요하지 않은 거라면 ui 단에서 메일주소 입력과 모니터링 요청해놓는 버튼을 만들어 놓고 (이건 그냥 지금 제가 생각한 아이디어 입니다)사용자가 명령을 내려놓으면 하루뒤에 해당 report를 받아볼 수 있도록 만 해도 될거같아요.. 데이터가 저장되는 공간은 추가로 고려해 보면 될 것 같고요. 
3. 2개 3개 정도가 guider 와 연결 된다고 하시는데 사실 기존 구현에서는 사용자가 command tab을 늘이면 한 브라우저 안에서도 connection 은  늘어나는 구조입니다 . 이것까지 감안하여서 web server 자체에서 동일 가이더와 커넥션을 맺을 풀 사이즈를 어느정도로 할 건지 강제하는것이 좋아보여요
4. --> 2번과 동일하게 얘기할 수 있을 것 같아요.
5. 실시간 헬스 체크 = 1번 시각화로 풀릴 수 있는 내용일까요??

결론적으로 제 의견은.
시각화, command tab 의 경우에는 기존처럼  통신하고 대신 max connection 을 정한다.
장기간 모니터링 데이터의 경우 어차피 가이더에서 report 파일을 떨궈주는 걸로 알고있는데 요청을 내려놓고 그걸 클라이언트한테 다운가능하게 하는게 어떻겠나 입니다.

**Comment by yoonje** [comment]
@iipeace @yangsso 
가능한 사용자가 가볍게 사용할 수 있게 하려면 별도의 스토리지를 잡아 먹지 않는 Web Socket 방향이 맞는 것 같습니다.

대체적으로 제 생각은 @yangsso 님과 동일합니다.  3번 ,4번에 대해서는 추가적으로 코맨트를 남기고 싶습니다.

3번에 대한 것은 guider를 구동하는 임베디드 보드의 환경을 저희가 알 수 없어 @iipeace 님이 max connection 개수와 report 주기를 어느 정도 정해주시는 것이 좋을 것 같습니다.

4번에 대한 것은 모니터링 동안은 가이더가 report 파일을 만들고 모니터링이 끝난 이후 가이더 서버에서 완성된 파일을 웹 서버로 전송하는 방식으로 report 파일을 처리하고 이후 이 데이터를 사용자가 분석하면 될 것 같습니다.

**Comment by iipeace** [comment]
@yangsso, @yoonje,
그럼 일단 논의된 부분은 이렇네요.

1. 기존 websocket 구조 유지

2. 기존 다중연결 방식 유지하면서 최대 접속 제한
-> 다중연결제한 개수는 기본 10개로 하고, 설정파일로 관리할수 있으면 좋을것 같습니다. 추가로 현재 Target에서 동작중인 Guider 프로세스 정보를 따로 보여주는 인터페이스도 추가할 수 있을까요? 비정상적으로 종료되지 않고 동작하는 작업들과 취소하지 못한 작업들을 관리하기 좋을 것 같습니다.

3. 리포트 주기
-> 3초 제안

4. Guider에서 생성하는 텍스트 기반 리포트 파일을 flask에서 png 파일로 변환(Guider에서 지원)하면, 이를 브라우저에서 출력하도록 하는 방법이 어떨까요?

**Comment by yangsso** [comment]
텍스트 파일을 굳이 png 로 바꿔야 하는 이유가 있을가 무엇인가요?

**Comment by iipeace** [comment]
장시간 쌓인 성능 데이터는 요악하더하도 텍스트 포맷으로 표현하여 사람이 분석하기 어렵습니다.
그래프로 변환된 png 파일 포맷의 출력이 필요하기 때문이에요 :)

**Comment by yangsso** [comment]
아 제가 이해를 잘못했습니다.저 는 텍스트를 이미지로 보게해준다는 건 지 알았어요 
결론은 가이더가 만든 그래프 이미지를 화면에 노출시키기만 하면 되는거니까 어렵지 않을거같아요

**Comment by yoonje** [comment]
@iipeace 
4번에 대해 코멘트 해주신 것에 질문 드리고 싶습니다. 리포트 파일을 flask에서 png 파일로 변환(Guider에서 지원)해서 브라우저에서 출력하는 방법을 권해주셨는데, Guider가 지원한다고 하신 것이 Guider 안에 matplotlib로 이미지 파일을 만드는 기능인가요? Guider에서 이미지 파일 생성을 지원한다면 웹서버에서 변환하지 않고 이미지 파일 자체를 수신하면 될 것 같습니다. 추가적으로 이미지 파일 사용 시 예상되는 문제점을 말씀드리면 이미지 파일을 브라우저에서 단순 출력하면 기존 UI와 다를 것이라는 점과 모니터링 시간이 길어지면 X축이 길어지므로 이미지의 특성상 시각화에 문제가 있을 것 같다는 점입니다.

**Comment by iipeace** [comment]
@yoonje,
대부분의 Target에는 matplotlib과 같이 무거운 패키지가 없기 때문에 flask에서 Guider 패키지를 이용해 pmg 생성하는 작업을 해야할 것입니다.

이전에도 @yangsso님이 얘기한 적이 있지만,
브라우저에서 실시간 그래프 출력 시 x축이 길어지면 부하로 작용하는 부분이 잇어서,
실시간 데이터 처리 시 최대 최근 60초 정도만 그리는 제약을 추가해야 할 것 같은데....
어떠신가요?

**Comment by yangsso** [comment]
네 그리고 추가로 거기서 오는 타임스탬프 포멧관련해서도 얘기가 필요할듯해요

**Comment by iipeace** [comment]
@yangsso,
타임스탬프는 x축 시작으로부터 상대값으로 변환할지 젛대값으로 할지 말씀이세요?

**Comment by yangsso** [comment]
네 기존에 오는값은 0.00000000 약간 이런 느낌이였떤걸로 기억이나요

**Comment by yoonje** [comment]
@iipeace 
matplotlib에서 png 파일로 저장하는 코드를 통해서 웹 브라우저에서 시각화 하게 될 경우 웹 브라우저에 png 파일 하나만 넘겨주게 될 것 같습니다. 이 경우 여러가지 문제가 예상되는데요.

1) 데이터가 커질 경우 png 파일의 y축은 고정이고 x축 크기만 커집니다. 브라우저에 억지로 넣을 경우 이미지 처리가 제대로 이뤄지지 않거나 시각화가 이상하게 될 수 있을 것 같습니다.

2) 브라우저에서는 이미지 크기나 픽셀 단위 정보밖에 얻을 수가 없어 x축의 일정 시간 단위로 이미지 분할이 필요하다면 matplotlib를 이용해 별도의 코드를 작성하여 처리하고 저장해야할 것 같습니다.

**Comment by iipeace** [comment]
@yoonje,
Guider에서 PNG 파일로 만들 때 matplotlib package로 그림을 그리게 되면,
x축은 자동으로 축소되어 적당한 비율로 그리게 됩니다.

그리고 matplotlib을 통해서 png 생성 후 브라우저에서 보여주는 것은 실시간 데이터가 아닌데,
혹시 실시간 시각화를 png 파일로 하시는 걸로 생각하셨나요?

**Comment by yoonje** [comment]
@iipeace 
음..제가 여쭤본 것은 x축이 너무 커지면 이미지 안에 표현되는 데이터가 너무 많아져서 문제가 될 수 있을 것 같다는 것인데요. 파일을 저장할 때 자동으로 축소가 되면 해상도(?)가 높아질 거에요. 브라우저에서 그릴 때는 JavaScript로 브라우저 안에 일정 크기 만큼 할당해서 이미지를 그리게 되니 가시성이 떨어지지 않을까요?

![제목 없음](https://user-images.githubusercontent.com/38535571/78892435-4e978700-7aa4-11ea-89b0-148fd16a8f1e.png)

약간 요런 느낌으로용.. 이 사진 기준으로 예를 들어보면 데이터가 늘어도 x축이 축소되어 사진 크기는 똑같이 저장될 텐데 x축의 길이가 10배, 20배, 30배가 되면 그래프 보기가 힘들지 않을까하는 생각입니다!

**Comment by iipeace** [comment]
@yoonje,
그 말씀이셨군요!
공유해주신 예제 그래프처럼 데이터가 커질수록 가시성이 떨어지는건 어쩔수 없을것 같아요.
사실 장시간의 데이터는 추세를 보는 것이기도 하고,
실사용에서는 장시간 프로파일링 시 데이터 크기를 고려해 샘플링 주기를 키우는 방식으로 쓰곤 합니다 :)

**Comment by yoonje** [comment]
@iipeace 
넵! 그럼 장시간 데이터는 샘플링 주기를 키우는 방식으로 해서 이미지를 브라우저에 그리는 것으로 하겠습니다! 추후 문제가 되면 보완하도록 하죠 :)
