### ISSUE TITLE
Same Process name Different PID

### ISSUE THREAD

**Issue by Jaeho211** [iipeace/guider#225]
I think Guider has a bug when there are processes which have same name.
Please refer below capture.
Left Screen is Htop and Right Screen is Guider (ver.3.9.7_200614 on python_2.7).
But the result is different.

![image](https://user-images.githubusercontent.com/51166611/84716120-4597ca00-afad-11ea-9ea7-e9d06dac4062.png)

**Comment by iipeace** [comment]
thanks for your report :)
could you share result for below commands?
1. ps -ef | grep frame
2. guider top -g frame
3. top -d 1

**Comment by Jaeho211** [comment]
![image](https://user-images.githubusercontent.com/51166611/84725079-bc8c8d00-afc4-11ea-96df-09a69847c5a1.png)

**Comment by iipeace** [comment]
I guess they are not processes but threads.
if you execute a below command then you can see tasks similar with one in htop.
    $ guider ttop
its about threads not processes.

**Comment by Jaeho211** [comment]
Thank you very much.
Yes. you are right.

Htop has confused column. I found below description.
In Htop, PID indicates Process/Thread ID
![image](https://user-images.githubusercontent.com/51166611/84738081-37b16b80-afe4-11ea-97e3-e54b001a7f55.png)
![image](https://user-images.githubusercontent.com/51166611/84738123-4861e180-afe4-11ea-81ca-3cbfd85478da.png)
