### ISSUE TITLE
"GUIDER reptop -Q" raise discontinuous stream

### ISSUE THREAD

**Issue by yoonje** [iipeace/guider#226]
Result
<img width="712" alt="discontinuous_stream" src="https://user-images.githubusercontent.com/38535571/85200131-c2210480-b32f-11ea-9473-1fac179c49a1.png">

Code
<img width="562" alt="caller" src="https://user-images.githubusercontent.com/38535571/85200187-2b087c80-b330-11ea-8ca2-b05c9935679b.png">
<img width="799" alt="function_ definition" src="https://user-images.githubusercontent.com/38535571/85200188-2e9c0380-b330-11ea-996c-2e1b567f81ce.png">

**Comment by iipeace** [comment]
@yoonje,
could you test it with "reptop -Q -a" command again?

**Comment by yoonje** [comment]
@iipeace 
I tried, but still raise discontinuous stream.

**Comment by yoonje** [comment]
fixed from commit 6e825a340dde6f6f3b90b6e3ec10db05ab7334a8
