### ISSUE TITLE
Error at drawing graph ([Error] Fail to find Detailed Statistics in guider.out)

### ISSUE THREAD

**Issue by talhagulbudak** [iipeace/guider#256]
Hi, I applied following steps and got an error with draw command. Maybe I am doing something wrong

- I get versions/3.9.7 of guider
- I ran following commands
    - sudo guider/guider.py rec -s .
    - sudo guider/guider.py report
    - sudo guider/guider.py draw guider.out
- It gives me this error : [Error] Fail to find Detailed Statistics in guider.out

As I understand, guide.py is looking a line that starts with "[Top" but my guider.out file doesn't have that line.

I also added my guider.out and guider.dat files.

[guider_files.zip](https://github.com/iipeace/guider/files/5739512/guider_files.zip)

**Comment by iipeace** [comment]
Hi!
I think you used old version Guider :)

Could you try again after git clone latest source from master branch in this repository?

# guider/guider.py rec -s
# guider/guider.py draw guider.dat

or

# guider/guider.py top -o
# guider/guider.py draw guider.out

They will require matplotlib and svgwrite packages. just use pip :)

First one is more detailed feature but big overhead,
Second one is general :)

**Comment by talhagulbudak** [comment]
Thank you so much it works with 
guider/guider.py top -o
guider/guider.py draw guider.out

**Comment by iipeace** [comment]
more useful command is...

# guider.py bgtop 
# guider.py stop
# guider.py draw PATH

Good luck! :)
