### ISSUE TITLE
Structure change for setup.py

### ISSUE THREAD

**Issue by jmg7173** [iipeace/guider#27]
`guider guider.conf guiderLib.c guiderMod.c guider.py guiderTest Makefile` goes to under `guider/` 
directory
* `./guider` &rarr; `./guider/guider`
* `./guider.conf` &rarr; `./guider/guider.conf`
* `./guiderLib.c` &rarr; `./guider/guiderLib.c`
* `./guiderMod.c` &rarr; `./guider/guiderMod.c`
* `./guider.py` &rarr; `./guider/guider.py`
* `./guiderTest` &rarr; `./guider/guiderTest`
* `./Makefile` &rarr; `./guider/Makefile`

**Comment by jmg7173** [comment]
Has problem with travis CI. So I'll fix and remerge it.

**Comment by iipeace** [comment]
okay!
it looks clear :)
