### ISSUE TITLE
Could you improve json option to use some data-science platform?

### ISSUE THREAD

**Issue by wikihur** [iipeace/guider#39]
I'd like to use the json data of guider for ELK(Elasticsearch Logstash Kibana) stack.

I request two function of guider.
- When I use json option, that will overwrite data for a file.
  Can you add some option for that function is either enable or disable?

- I wish there was a separate field with a timestamp.

Thanks.

**Comment by iipeace** [comment]
dear @wikihur,
I added 'timestamp' field on root in json-format output.
and if you want to append json data to the end of file then use "-d t" option.
"-d" means disable, "t" means truncate.
thanks!
