### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by kritikaal** [iipeace/guider#42]
Hello,

New to linux, python and github. Newb, in short :) and I would like a little push on the below.

When I execute commands with guider, I get the following error

"ValueError: too many values to unpack" ( details attached )
[ValueError.txt](https://github.com/iipeace/guider/files/2851109/ValueError.txt)

Release:
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.2
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"

Python 2.7.15 (default, Jan 10 2019, 23:20:52) 
[GCC 8.2.1 20181127] on linux2

Python 3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127] on linux

From a search that I did on this error, I suspect it might be related to the version of python that I use; "python >= 2.7" means python 2.7 and later versions of python 2 and not 3, right? I tried to run it through python 2 though, without success.

Any bells ringing?

Thank you in advance.

Best Regards,

krit

**Comment by iipeace** [comment]
This is diskstat in kernel version 4.18+ issue :)
Could you check it again with recent 47a84b8eb1b354d38c65a6c118ce22386a161539 commit?

**Comment by kritikaal** [comment]
Dear iipeace,

Thank you very much for the quick and accurate reply and apologies if this bug was already mentioned in the issues and i missed it.

Indeed, I replaced the .py file with the new one and the issue is resolved.

Thanks again.

krit

**Comment by iipeace** [comment]
dear krit,

this bug is new one!
I also thanks for your reporting!
Please don't hesitate to write your problem or idea here :)

thanks.
