### ISSUE TITLE
Vue.js 코드에 대한 개선 의견

### ISSUE THREAD

**Issue by MoonHyuk** [iipeace/guider#51]
안녕하세요, `agent` 브렌치에 있는 Vue.js 관련 코드를 읽고 몇가지 의견이 있어 이슈 남깁니다. 제 의견이 절대 맞는 것이 아니고, 제가 부족하여 잘못된 의견일수도 있으니 다른 분들도 여러 생각을 공유해주시면 좋을거 같습니다.

1. 빌드된 파일이 git으로 관리되고 있음
https://github.com/iipeace/guider/tree/bf45611274d8e78a84235f1f39096d78c7b4dc48/agent/static
위 폴더 하위에 있는 파일들 같이 vue 빌드 이후 생성되는 파일들은 .gitignore에 넣는게 좋다고 생각합니다. 빌드 결과물이 git으로 관리된다면 여러가지 문제점이 있습니다.
    1. 프론트엔드의 변경점이 있을때마다 작업자들은 까먹지 말고 build를 한 후 커밋해야 합니다. 실수로 빌드 결과물을 올리지 않으면 코드와 빌드 결과물간 싱크가 안맞는 경우가 생깁니다.
    2. 동시에 두 작업자가 작업을 할 때, 완전히 다른 부분을 수정했더라도 빌드 결과물을 각자 올린다면 무조건 merge conflict가 발생될것으로 예상됩니다.
    3. 일반적으로 개발 환경에서의 빌드 결과물과 배포 환경에서의 빌드 결과물은 다릅니다. 누군가 실수로 기존 파일을 개발 환경의 빌드 결과물로 덮어쓰기 한다면 문제가 생길수도 있습니다.
    4. 사실 코드(+ 빌드 환경)가 같다면 빌드 결과물도 같을것이므로 두 개를 같이 git으로 공유하는 건 중복입니다.

2. 프론트엔드를 라우팅 하는 방법
https://github.com/iipeace/guider/blob/bf45611274d8e78a84235f1f39096d78c7b4dc48/agent/__init__.py#L63-L66
현재는 위와 같이 프론트엔드를 라우팅하고 있습니다.
하지만 이 방법으로는 프론트엔드에 다른 라우트를 추가하는게 어렵습니다.
예를들어 `www.some-domain.com/admin` 이나 `www.some-domain.com/login` 같은 경로를 만들고 싶으면 어떻게 하나요?

    또한 `index.html`은 빌드 결과물이므로 1번 의견에 의하면 빌드 결과물들은 git에서 제외되어야 하고, 소스 코드는 빌드 결과물에 의존적이지 않아야 합니다.

    이를 개선하기 위한 좋은 방법은 일반적인 경로로 들어오면 프론트엔드에서 처리를 해주고, 경로 앞에 `/api`가 있다면 백엔드(flask)에서 처리를 하도록 프록시 설정을 해주는 것입니다. 개발 환경이라면 vue의 [devserver-proxy](https://cli.vuejs.org/config/#devserver-proxy)를 이용하고, 배포 환경이라면 `nginx`등에서 설정을 하면 될거 같습니다([예시](https://stackoverflow.com/questions/54582634/how-to-deploy-a-flask-vue-js-web-application))

3. 프론트엔드 빌드 시 오류
[package.json](https://github.com/iipeace/guider/blob/bf45611274d8e78a84235f1f39096d78c7b4dc48/agent/front_vuejs/package.json#L13)에 명시되어 있는 대로 `npm run dev` 또는 `npm run build`를 실행할 시, `build/build.js` 파일을 찾을수 없다는 오류가 납니다. 실제로 `build`라는 폴더가 존재하지 않는데 혹시 제가 놓친 부분이 있을까요?
```
root@goorm:/workspace/guider/agent/front_vuejs((detached from origin/agent))# npm run build

> guider_front@1.0.0 build /workspace/guider/agent/front_vuejs
> node build/build.js

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module '/workspace/guider/agent/front_vuejs/build/build.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by iipeace** [comment]
@MoonHyuck,
리뷰 및 리포트 감사합니다!

1. 소스와 빌드결과물을 동일 git으로 관리
이 부분은 현재 개발상태가 단순 feasibility만 보기 위한 단계라서 정식 개발 방식은 아닙니다. 
다른 분이 개발한 내용을 제가 clone하여 즉시 실행시켜보기 위해 agent branch에서만 소스와 빌드결과를 모두 올려두었습니다.
이제 이 구조만 참고하여 처음부터 개발해야 합니다. ;)
일단 다같이 작업을 시작하면 소스만 git에 올리고 배포 방식은 따로 논의할 예정입니다.

2. 프론트엔드 라우팅
역시나 vue와 flask를 모르고 임시 구현한 내용이며,
현재 제가 flask 공부 중입니다 ;)

그런데 flask에서 하나하나 라우팅 해주는거 외에 프론트에서 직접 하기도 하는군요?
제 생각은 앞으로도 백엔드는 flask로 쭉 갈거지만 프론트는 바뀔 가능성도 있으니 가능하면 백엔드에서 대부분 라우팅을 하는게 좋을 것 같은데,
어떻게 생각하세요?
백엔드 프락시는 저도 살펴볼게요.

3. 빌드에러
확인해보고 말씀드리겠습니다.

**Comment by MoonHyuk** [comment]
1. 앗 제가 설레발이었군요... 넵 알겠습니다:)
2. 음 이부분은 저도 조사를 좀 더 해보니 지금의 구조를 많이 쓰긴 하는군요. [예시]를 보면 개발 환경일 땐 프론트엔드 개발 서버로 요청을 다시 보내고, 아니면 index.html을 불러오는 구조로 되어있네요. 하지만 여기서도 [프론트엔드의 라우팅](https://github.com/oleg-agapov/flask-vue-spa/blob/master/frontend/src/router/index.js)은 따로 있습니다.
    어느 url에서 어떤 페이지를 보여줄지 같은 UI의 라우팅은 프론트엔드에서, guider와 통신하는 부분은 flask에서 분리하여 처리하는게 이해하기가 편할거 같습니다. :)

**Comment by Agrajak** [comment]
2. 저도 찾아보고 있는데 [Vue Router 공식 문서](https://router.vuejs.org/kr/guide/essentials/history-mode.html#%EC%84%9C%EB%B2%84-%EC%84%A4%EC%A0%95-%EC%98%88%EC%A0%9C)를 참고하면 도움이 될 것 같습니다. 문혁님이 올리신 예시대로 하면 큰 문제 없을 것 같아요

3.  원래 vue-cli 2.x (지금은 보통 3.0을 사용합니다.)로 프로젝트를 만들면 build 폴더에 빌드에 필요한 webpack 설정이나 이것 저것 파일들이 포함되는데 `.gitignore`에 `build/`가 포함되어서 누락된 것 같아요!

**Comment by iipeace** [comment]
flask-vue-spa라는 좋은 레퍼런스가 있었네요!
참고해서 구조랑 기본코드 정리하면 좋을 것 같습니다 :)

보니까 dist 디렉토리도 같이 관리하고 있고,
@Agrajak님 말씀대로 build도 있어야 하네요.
Vue Router 공식문서 참고하시지요 :)

**Comment by MoonHyuk** [comment]
@iipeace vue-cli로 뷰 프로젝트를 자동 생성하면 dist 폴더는 gitignore에 들어가요. git에 관리되지 않는게 기본 옵션이라 특별한 이유가 없다면 따르는게 좋다고 생각됩니다!

**Comment by iipeace** [comment]
@MoonHyuk,
dist가 빌드 결과물(배포용 파일)인가요?

**Comment by MoonHyuk** [comment]
@iipeace 네 맞습니다
