### ISSUE TITLE
Guider 웹 구조 설계 참고를 위한 정리

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#52]
설계에 필요한 고려사항 그냥 생각나는데로 정리했습니다.
더 필요한 부분이나 잘못 적혀있는 부분 comment 로 자유롭게 의견 부탁드립니다.

서비스 정의 - 시스템 헬스 체크.
프로젝트 목적 - 사용자 요구사항에 유연하게 대응하는 gui 개발 + 누구든 쉽게 사용할 수 있기를 바람.??

요구사항 - 

**Front(Vue)** 
1. UI 요구사항에 따른 component 구조 정리
2. 상태 공유 관련 ( eventbus, vuex...)
3. i18n 국제화

**backend(Flask)**
1. 요구 사항 정리에 따른 api 리스트업.
2. api 스펙 정의
3. command 요청 로직 정리.

**+a**
1. validation
2. Test
3. coding convention
4. 빌드 환경
5. web 로깅 관련
6. infra 세팅 관련.

**추가로 참고하면 좋을 것 같아서 정리.**

Ngrinder
-Architecture 관련 문서 : https://github.com/naver/ngrinder/wiki/Architecture
-UI 참고 문서 : https://github.com/naver/ngrinder/wiki/Screen-Shot
Repo 구성의 경우 한 repo 에 모두 정리 되어있음.
- front : ngrinder-frontend,  vue 프로젝트로 구성 
- backend : ngrinder-controller, spring 프레임 웍으로 구성. 요청에 따라 ngriner-core 메소드 호출
- core logic : ngrinder-core

ES beat 시각화 화면 참조 (metricbeat,https://www.elastic.co/kr/products/beats/metricbeat)

애초에 flask 앱 자체도 워낙 작게 만들어져 있고 web 자체가 별도의 서버에서 동작한다면 굳이 flask 일필요는 없을 듯.. node여도..

**Comment by iipeace** [comment]
@yangsso,
장리해주셔서 감사합니다~!! :)
특히 backend 쪽 중요한 내용이네요.
+a 부분은 나중에 기본기능 나오고 시작하면 좋을것 같습니다 :)

현재도 ES beat을 지원하기 위한 JSON 형식 포맷 출력은 구현되어 있습니다,
시각화 예제들 보고 골라서 적용하는것도 좋은 아이디아네요!

일단 요구사항 정리하면 알려주신것들 반영하여 진행하겠습니다~!! :)

**Comment by iipeace** [comment]
backend(Flask)
1. 요구 사항 정리에 따른 api 리스트업
2. api 스펙 정의
3. command 요청 로직 정리

이 부분은 이제 정리 되었다고 봐도 될까요~?? :)
