### ISSUE TITLE
flask 가 바라보고 있는 view 경로 변경.

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#53]
현재는 빌드된 결과물을 따로 templates 파일로 옮겨놓고
해당 파일을 바라보게 되어있음
아래와 같이 빌드된 파일이 떨어지는 위치로 세팅 변경 필요.

app = CustomFlask(__name__, 
        template_folder='../agent_frontend/guider-vue/dist', 
        static_folder='../agent_frontend/guider-vue/dist/static')

vue build 한 js 파일이 아예 따로 떨어지도록 세팅 필요 
index.html 따로 두고 해당 js import 시켜서 flask 에서 해당 view를 보도록..

config/index.js 에 아래와 같이 세팅.
'use strict'

const path = require('path')
const distPath = '../Scripts/bundle'

module.exports = {
  build: {
    assetsRoot: path.resolve(__dirname, distPath),
    assetsPublicPath: '/',
    useEslint: true,
    showEslintErrorsInOverlay: false,
    dev: {
    },
    prod: {
    }
  }
}

**Comment by iipeace** [comment]
내, 저도 따로 분리하는것에 동의합니다! :)
