### ISSUE TITLE
코드 수정 하면서 논의 필요한 부분 정리

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#59]
기존 에러나던 부분 고치면서 몇가지 수정해서 pr 했습니다. 

PR : https://github.com/iipeace/guider/pull/58

(기존 프론트 코드는 빌드가 안되고  너무 무겁고 해서 어차피 새로 개발하면 참고만 하면 될거같아서. Socket 부분만 남기고 다 날렸어요)

저도 잘 몰라서 혹시 이상한 부분 있으면 리뷰 해주시면 감사할거같아요~

1. Flask 에서 host_url 을 vue로 넘겨주고 해당 url로 vue에서 socket 연결하는 방식으로 수정해서 잘 되는건 확인했습니다. 

2. 기존 구조에서 vue 웹팩 빌드 관련해서 조금 변경해서 npm run build하면 guider-vue/static/js 아래 빌드된 결과 들어가도록 해놨습니다.

3. 아예 flask에서 static 경로를 지정할 수도 있어서요.
Vue 프로젝트 아래 static 폴더 두고 사용하는게 더 좋은것도 같아서 해놨는데 flask.플젝 아래 둘지는 이부분 의견 부탁드려요.

4. 그리고 현재는 agent —> backend 프로젝트 dir
Guider-vue —> agent아래 frontend 프로젝트로 되어 있는데 
아예 디렉토리 분리해서 나눠놨는데 agent 아래 둘지 의견 부탁드려요

5. local환경에서 nom run dev 하면 Hot reload 은 가능한데 flask와 통신시 cors 오류 있습니다. 요부분 수정해주실 분 수정해주셔도 좋을 것 같아요.

6. 지금은 제가 임시로 guider-vue 로 front 를 냅뒀는데요 큰 틀에서 네이밍 관련해서는 얘기해서 정하는게 좋을거 같아서 이부분도 의견 부탁드립니다.

추가로 agent 디렉토리 아래에 requirements.txt 추가해놨는데
Pip install -r requirements.txt 하면 flask run을 위해 필요한 패키지 설치되니까 참고하시면 좋을거같아요

**Comment by iipeace** [comment]
1. static 위치
저는 빌드 결과물을 flask dir(agent) 아래 static으로 두는거에 한표!
front는 나중에 바뀔수도 있기 때문에 그게 더 좋을것 같아서요~

2. dir 구조
guider-vue가 agent 안으로 들어가는게 좋을것 같은데,
그랬을때 개발/배포 시에 어려움이나 단점이 있을까요~??

3. naming
guider-vue가 agent dir 내부로 들어간다면,
front-vue를 제안합니다~!!

**Comment by iipeace** [comment]
@KangWooJin,
여기서 dir 구조에 대해 얘기하면 좋을 것 같습니다 :)
