### ISSUE TITLE
간단한 웹 아키텍쳐 정리.

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#67]
@iipeace  추가로 더 붙여주시면 될 것 같아용 :)

<img width="674" alt="KakaoTalk_20190921_163745031" src="https://user-images.githubusercontent.com/18661008/65403983-8e9d6200-de11-11e9-81f5-a2fc07ba66bf.png">
<img width="511" alt="KakaoTalk_20190921_163746253" src="https://user-images.githubusercontent.com/18661008/65403984-8f35f880-de11-11e9-8618-f888afb4f076.png">

**Comment by iipeace** [comment]
![Guider Web](https://user-images.githubusercontent.com/15862689/65405733-20a86900-de18-11e9-9fd1-8bcd67bedce0.png)

공유해주신 내용 참고하여 이렇게 수정해 보았는데,
어떨까요~??

**Comment by KangWooJin** [comment]
해당 이미지 readme에 들어가면 좋겠네요! #78

**Comment by iipeace** [comment]
구조 관련해서 다른 의견 없으면 정리해서 readme에도 추가하겠습니다! :)
