### ISSUE TITLE
guider <> flask <> vue  통신관련 의견 정리.

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#68]
시나리오 1.

최초에 server connect http 리퀘스트를 보내면(interval time 과 함께)
flask는 guider 와 통신해서 데이터를 받아서 db에 쓰기 시작한다.
Socket 통신은 브라우저가 켜져있는 동안 지속되고 데이터를 가져오는데 성공하면 client 에게 요청을 주고 그 때 client 는 다시 데이터를 읽어간다.

Flask 의 경우에는 서비스가 돌면서  데이터를 1초마다 쌓아주고.
Client는 interval time 에 맞춰서 화면을 refresh 해준다. ( http 통신을 통해 데이터를 가져온다)

브라우저와 socket 통신이 끊기거나 사용자가 connect stop을 요청할 시 db 저장을 중단한다.

+ 뷰단에서 시계열 데이터를 그릴경우 고려할 부분이 있음..
Disk 부하..

시나리오 2.

모든 client는 flask 서버와 각각 소켓통신을 통해 연결되고 flask는 내부에서 guider와 tcp 통신을 하여 필요한 데이터를 받아오고 화면에 뿌려준다. 저장이 필요한 데이터를 요청하는 command 의 경우에만 db에 저장한다.
(Command 명령어에 따라서 json 따로 오도록 작업 가능해야함)

이것도 나쁘지 않은게.. 다른 시스템 모니터링 툴도 연결 끊기면 끊기는데로 그래프 그려줌.

**시나리오 3.
두개를 섞는 방법인데 저장이 필요없는데이터 ( 연결성이 그렇게 보장되지 않아도 되는 데이터) 의 경우에는 socket통신. 
그 외의 중요하거나 저장이 필요한 것들은 소켓 연결이 되있으면. Db 에 데이터 저장 후 http 통신.**

**Comment by iipeace** [comment]
최초 접속 시 보여지는 메인페이지에서는 타겟과 접속 기능 제공,
접속 된 이후로는 자동으로 실시간 데이터에 한해 비동기 시각화 정보(차트) 업데이트 시작.

별도 페이지에서는 모든 시각화 데이터를 DB로 저장시키기 시작하는 기능이 있고,
저장을 시작한 이후로는 그 페이지에 접근 시 언제라도 저장된 과거 데이터들로 시각화 정보 출력.

적당히 스토리지 DB와 메모리 캐싱을 해야할 것 같네요~!! :)

**Comment by sssunda** [comment]
1로 하게 되면 소영님이 말씀하신 것 처럼 부하가 일어날 수 있으니 제외한다면,
과거의 데이터도 보기 위해서는 시나리오 3으로 가야하지 않을까요? 사용자는 어떤 커맨드가 db에 저장하는 것인지 모를 수 있으니 저희가 db에 저장할 항목을 정해주는게 좋지 않을까. 라는 것이 저의 생각입니다.

**Comment by iipeace** [comment]
@sssunda,
맞습니다~!!
하여 그러한 데이터는 #69에서 논의하면 좋을 것 같습니다 :)
