### ISSUE TITLE
필수 Data 저장관련 논의

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#69]
어떤 db를 쓸지 어떻게 데이터를 저장할지 의사결정이 필요한데
이 부분에 대해서 평화님이 우선 저장할 데이터들이 뭔지 알려주셔야 할거같아요.
comment로 리스트업 부탁드려요.
@iipeace

**Comment by iipeace** [comment]
@yangsso,
일단 현재 Guider 통해서 실시간으로 얻어오는 JSON 데이터 공유드립니다.
각 항목(key) 옆에 //와 함께 정보 내용 및 표시해야하는 속성(TEXT/CHART) 기입하였습니다.
보시고 의견 주시기 바랍니다.

<pre><code>
{
  "task": {	// System Task Info (TEXT)
    "nrThread": 1057, 
    "nrBlocked": 0, 
    "nrCtx": 641, 
    "nrProc": 314
  }, 

  "mem": {	// System Memory Info (CHART)
    "available": 58571, 
    "kernel": 705, 
    "nrMinFlt": 289, 
    "anonDiff": 1, 
    "availableDiff": -1, 
    "pgRclmFg": 0, 
    "cache": 9891, 
    "slabDiff": 0, 
    "free": 49691, 
    "anon": 4017, 
    "pgDirty": 83, 
    "file": 8847, 
    "freeDiff": -1, 
    "pgMlock": 1816, 
    "pgRclmBg": 0, 
    "total": 64304, 
    "slab": 1044, 
    "fileDiff": 0
  }, 

  "timestamp": 707538.4,  // Timestamp (REFERENCE)

  "storage": {	// System Storage Info (CHART)
    "/dev/loop1": {
      "avq": 0, 
      "read": 0, 
      "mount": {
        "major": "7", 
        "fs": "squashfs", 
        "option": "ro,nodev,relatime", 
        "soption": "ro", 
        "path": "/snap/core/7396", 
        "mountid": "52", 
        "minor": "1"
      }, 
      "favail": 0, 
      "free": 0, 
      "iowtime": 0, 
      "write": 0, 
      "writetime": 0, 
      "usage": 88, 
      "iotime": 0, 
      "total": 88, 
      "usageper": 100, 
      "readtime": 0
    }, 
    "total": {
      "avq": 0, 
      "read": 0, 
      "mount": null, 
      "favail": 43360566, 
      "free": 89817, 
      "iowtime": 0, 
      "write": 0, 
      "writetime": 0, 
      "usage": 137850, 
      "iotime": 0, 
      "total": 227667, 
      "usageper": 60, 
      "readtime": 0
    }, 
    "/dev/sdb": {
      "avq": 0, 
      "read": 0, 
      "mount": {
        "major": "0", 
        "fs": "tmpfs", 
        "option": "", 
        "soption": "rw,size=6584736k,mode=755", 
        "path": "/run/snapd/ns", 
        "mountid": "197", 
        "minor": "23"
      }, 
      "favail": 8229958, 
      "free": 6412, 
      "iowtime": 0, 
      "write": 0, 
      "writetime": 0, 
      "usage": 18, 
      "iotime": 0, 
      "total": 6430, 
      "usageper": 0, 
      "readtime": 0
    }, 
  }, 

  "system": {	// System ETC Info (TEXT)
    "load5m": 0.08, 
    "uptime": 707538.4, 
    "nrSoftIrq": 346, 
    "nrIrq": 260, 
    "load15m": 0.08, 
    "interval": 1.0300000000279397, 
    "pid": 25089, 
    "load1m": 0.12
  }, 

  "process": {	// Process Info (CHART)
    "216": {	// Process ID
      "nrFlt": 0, 
      "nrThreads": "1", 
      "vss": 0, 
      "sched": "C0", 
      "mem": 0, 
      "fd": "64", 
      "dtime": 0, 
      "bread": 0, 
      "PID": "216", 
      "life": "8d:04:32:16", 
      "bwrite": 0, 
      "btime": 0, 
      "code": 0, 
      "comm": "scsi_eh_3", 
      "stime": 0, 
      "shared": 0, 
      "ttime": 0, 
      "PPID": "2", 
      "swap": 0, 
      "utime": 0
    }, 
    "217": {
      "nrFlt": 0, 
      "nrThreads": "1", 
      "vss": 0, 
      "sched": "C-20", 
      "mem": 0, 
      "fd": "64", 
      "dtime": 0, 
      "bread": 0, 
      "PID": "217", 
      "life": "8d:04:32:16", 
      "bwrite": 0, 
      "btime": 0, 
      "code": 0, 
      "comm": "scsi_tmf_3", 
      "stime": 0, 
      "shared": 0, 
      "ttime": 0, 
      "PPID": "2", 
      "swap": 0, 
      "utime": 0
    }, 
    "214": {
      "nrFlt": 0, 
      "nrThreads": "1", 
      "vss": 0, 
      "sched": "C0", 
      "mem": 0, 
      "fd": "64", 
      "dtime": 0, 
      "bread": 0, 
      "PID": "214", 
      "life": "8d:04:32:16", 
      "bwrite": 0, 
      "btime": 0, 
      "code": 0, 
      "comm": "scsi_eh_2", 
      "stime": 0, 
      "shared": 0, 
      "ttime": 0, 
      "PPID": "2", 
      "swap": 0, 
      "utime": 0
    }, 
  }, 

  "swap": {	// System Swap Info (CHART)
    "usage": 0, 
    "swapout": 0, 
    "total": 65413, 
    "usageDiff": 0, 
    "swapin": 0
  }, 

  "net": {	// System Network Info (CHART)
    "inbound": 52, 
    "outbound": 52
  }, 

  "cpu": {	// System CPU Info (CHART)
    "kernel": 0, 
    "iowait": 0, 
    "nrCore": 8, 
    "idle": 99, 
    "percore": {	// System Core Info (CHART)
      "0": {
        "kernel": 0, 
        "irq": 0, 
        "idle": 100, 
        "user": 0, 
        "iowait": 0, 
        "total": 0
      }, 
      "1": {
        "kernel": 0, 
        "irq": 0, 
        "idle": 100, 
        "user": 0, 
        "iowait": 0, 
        "total": 0
      }, 
      "2": {
        "kernel": 0, 
        "irq": 0, 
        "idle": 100, 
        "user": 0, 
        "iowait": 0, 
        "total": 0
      }, 
      "3": {
        "kernel": 0, 
        "irq": 0, 
        "idle": 100, 
        "user": 0, 
        "iowait": 0, 
        "total": 0
      }, 
      "4": {
        "kernel": 0, 
        "irq": 0, 
        "idle": 100, 
        "user": 0, 
        "iowait": 0, 
        "total": 0
      }, 
      "5": {
        "kernel": 0, 
        "irq": 0, 
        "idle": 100, 
        "user": 0, 
        "iowait": 0, 
        "total": 0
      }, 
      "6": {
        "kernel": 0, 
        "irq": 0, 
        "idle": 100, 
        "user": 0, 
        "iowait": 0, 
        "total": 0
      }, 
      "7": {
        "kernel": 0, 
        "irq": 0, 
        "idle": 98, 
        "user": 1, 
        "iowait": 0, 
        "total": 2
      }
    }, 
    "user": 0, 
    "irq": 0, 
    "total": 1
  }, 

  "block": {	// System Block Device Info (CHART)
    "read": 0, 
    "write": 0, 
    "nrTask": 0, 
    "nrMajFlt": 0, 
    "ioWait": 0
  }
}
</code></pre>

**Comment by yangsso** [comment]
주석 달아주신 부분이 각 따로 사용되는 모델이라고 보면 되죵?

**Comment by iipeace** [comment]
@yangsso,
네, 맞습니다~!!

**Comment by iipeace** [comment]
최초 메인페이지 접속 시 출력할 차트 내용 일부 우선 공유드립니다.

1. CPU 정보 (꺾은선그래프)
{ 'CPU':  {'total'} }
Label로 'nrCore' 값 추가
단위는 %

2. Memory 정보 (꺾은선그래프)
{ 'mem':  {'available'} }
Label로 'total' 값 추가
단위는 MB

3. Storage 정보 (꺾는선그래프)
{ 'storage':  { 'total': { 'free' } } }
Label로 { 'total': { 'total' } } } 값 추가
단위는 MB

4. Network 정보 (꺾는선그래프)
{ 'net':  { 'inbound', 'outbound' } }
단위는 Byte
