### ISSUE TITLE
vue router 동작 확인

### ISSUE THREAD

**Issue by KangWooJin** [iipeace/guider#73]
`__init__.py`의 `templates`쪽과 static folder간에 file 경로 셋팅 불일치로 router 동작이 안되는 현상 해결

1. __init__.py의 `template_folder`를 `static/index.html`을 볼 수 있게 설정 하기
2. `static_folder`를 build된 directory에 `js`, `css`을 볼 수 있게 설정

- [ ] `/` 페이지 진입 시 페이지 
- [ ] 좌측 탭 클릭시 다른 페이지 표시

현재 에러 상황
![image](https://user-images.githubusercontent.com/17493311/65524611-10cc7a00-df29-11e9-81d8-d1c38ce0b9a8.png)

**Comment by yangsso** [comment]
@KangWooJin  님 
1번 이 이슈는 얘기를 좀 해봐야 할 것 같아요.
기본적으로 얘기했던 운영배포 세팅은 flask 구조에 vue build  결과물 js를 import 하는 거였어서.

static folder 도 위치 결정되면 flask 쪽에서 세팅하면 되니 제가 이슈 따로 하나 만들어 놓을게요 comment 부탁드려용

**Comment by KangWooJin** [comment]
@yangsso 님 flask에서는 `template_folder`랑 `static_folder`를 써야 하는걸까요? 
build된 디렉토리에 index.html을 기준으로 js, css를 보게 하는게 더 편하지 않을까도 생각듭니다

**Comment by yangsso** [comment]
넵 ~ front 단에 내용은 다 아래서 관리한다고 생각했을때 크게 상관은 없는 것 같아요.
저 이슈는 우진님이나 혹은 다른 분이 front directory 이관 진행해주시면 제가 해결할게요~

**Comment by KangWooJin** [comment]
build된 파일을 사용할 때는 배포시에만 사용하고 실제 개발할 때는 flask랑 vue쪽 같이 띄우고 vue쪽 proxy 설정을 통해서 flask로 통신하는게 편할거 같아요!

어느정도 설명을 못 한 부분이 있네요 ㅠㅠ flask에 `template_folder`, `static_folder`는 써야하고 경로 설정이 중요한거였네요!

**Comment by yangsso** [comment]
app = CustomFlask(__name__, 
        template_folder='templates',
        static_folder='../guider-vue/static')

이런식으로 세팅하면 되요~

**Comment by yangsso** [comment]
flask <>vue 로컬 세팅하면서  proxy 관련해서 https://github.com/yangsso/guider/blob/b8a22395d7006f568f9d0ca12aa23dc73357609c/guider-vue/config/index.js#L13

예전에 작업해놨는데.. 이거 cors 오류 있었는데 제가 아직까지 못보고 있긴해요..ㅎㅎ

**Comment by KangWooJin** [comment]
혹시 빌드 된 파일을 repo에 관리할 필요가 있을까요?

**Comment by KangWooJin** [comment]
> app = CustomFlask(**name**,
> template_folder='templates',
> static_folder='../guider-vue/static')
> 
> 이런식으로 세팅하면 되요~

guider-vue의 build시에 build 결과물을 `agent/.`에 설정하려고 해서 해당 방식으로 변경할까 하는데
static 파일의 경로를 잘 못 찾는거 같았어요~

`template_folder='./static'`,
`static_folder='./static'`

**Comment by yangsso** [comment]
> 혹시 빌드 된 파일을 repo에 관리할 필요가 있을까요?

빌드 된 결과물이 git 에 푸쉬 되야 하나에 대한 얘기시면 아니라고 생각해요

**Comment by yangsso** [comment]
> > app = CustomFlask(**name**,
> > template_folder='templates',
> > static_folder='../guider-vue/static')
> > 이런식으로 세팅하면 되요~
> 
> guider-vue의 build시에 build 결과물을 `agent/.`에 설정하려고 해서 해당 방식으로 변경할까 하는데
> static 파일의 경로를 잘 못 찾는거 같았어요~
> 
> `template_folder='./static'`,
> `static_folder='./static'`

넵 요 이슈는 dir 경로 완전히 정해지고 수정되면 제가 수정해서 pr 할게요
