### ISSUE TITLE
Flask Single Page Application 적용을 위한 route 설정 변경

### ISSUE THREAD

**Issue by KangWooJin** [iipeace/guider#79]
해당 issue와 관련 있음 #73 

* `/` 하위로 요청이 들어오는 경우 index.html 파일로 전달 해주는 방식으로 변경 필요

refer : https://codeburst.io/full-stack-single-page-application-with-vue-js-and-flask-b1e036315532

**Comment by yangsso** [comment]
요 이슈는 flask  app directory 세팅되고 view.py 따로나오면 그때 적용하는걸로~

**Comment by jeffin07** [comment]
@yangsso  so you want create a flask server which render an html page in "/" route

**Comment by iipeace** [comment]
#110에서 @MoonHyuk님이 fixed 처리 하신 것 같으니,
확인 해주셔요 :)
