### ISSUE TITLE
security issues

### ISSUE THREAD

**Issue by iipeace** [iipeace/guider#83]
We found a vulnerable dependency in a repository you have security alert access to.

1. Known moderate severity security vulnerability detected in js-yaml < 3.13.0 defined in yarn.lock.
--
yarn.lock update suggested: js-yaml ~> 3.13.0.

2. Known critical severity security vulnerability detected in lodash.mergewith < 4.6.2 defined in yarn.lock.
--
yarn.lock update suggested: lodash.mergewith ~> 4.6.2.

3. Known high severity security vulnerability detected in set-value < 2.0.1 defined in yarn.lock.
--
yarn.lock update suggested: set-value ~> 2.0.1.

4. Known high severity security vulnerability detected in js-yaml < 3.13.1 defined in yarn.lock.
--
yarn.lock update suggested: js-yaml ~> 3.13.1.

5. Known high severity security vulnerability detected in tar < 2.2.2 defined in yarn.lock.
--
yarn.lock update suggested: tar ~> 2.2.2.

6. Known moderate severity security vulnerability detected in webpack-bundle-analyzer < 3.3.2 defined in yarn.lock.
--
yarn.lock update suggested: webpack-bundle-analyzer ~> 3.3.2.

7. Known high severity security vulnerability detected in deep-extend < 0.5.1 defined in yarn.lock.
--
yarn.lock update suggested: deep-extend ~> 0.5.1.

8. Known moderate severity security vulnerability detected in stringstream < 0.0.6 defined in yarn.lock.
--
yarn.lock update suggested: stringstream ~> 0.0.6

9. Known high severity security vulnerability detected in mixin-deep < 1.3.2 defined in yarn.lock.
--
yarn.lock update suggested: mixin-deep ~> 1.3.2.

10. Known moderate severity security vulnerability detected in fstream < 1.0.12 defined in yarn.lock.
--
yarn.lock update suggested: fstream ~> 1.0.12.

11. Known high severity security vulnerability detected in cryptiles < 4.1.2 defined in yarn.lock.
--
yarn.lock update suggested: cryptiles ~> 4.1.2.

**Comment by DROOPER** [comment]
Hi, can I submit a PR in order to fix those security issues?

**Comment by iipeace** [comment]
sure :)

**Comment by iipeace** [comment]
Not all dependency issues are fixed yet ;(

1. Upgrade lodash to version 4.17.13 or later. For example:
lodash@^4.17.13:
  version "4.17.13"

2. Upgrade lodash.template to version 4.5.0 or later. For example:
lodash.template@^4.5.0:
  version "4.5.0"

3. Upgrade lodash.defaultsdeep to version 4.6.1 or later. For example:
lodash.defaultsdeep@^4.6.1:
  version "4.6.1"

**Comment by DROOPER** [comment]
Fixing them right now!

**Comment by iipeace** [comment]
All dependency issues are fixed :)
