### ISSUE TITLE
.gitignore 파일 수정(다양한 개발 환경 대응, tip 공유)

### ISSUE THREAD

**Issue by yeombang87** [iipeace/guider#87]
1. 오픈소스 특성상 다양한 개발 환경에 맞는 .gitignore 파일로 수정
- OS support : Windows, macOS
- Development tool : VS Code, WebStorm, SublimeText
- Other : Node, Vue, Python

2. 아래에서 개발환경에 맞는 .gitignore 파일을 쉽게 생성
- https://www.gitignore.io/

**Comment by Agrajak** [comment]
일단 .vscode 추가했습니다!
