### ISSUE TITLE
Tcp 소켓 옵션

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#88]
기본적으로는 client 요청이 더이상 오지 않으면 tcp 통신을 끊지만 

Guider 에서 오는 데이터가 일정시간 이상 지나는 경우에도 tcp 연결 끊어버리는 예외처리 필요

https://blog.cloudflare.com/ko/when-tcp-sockets-refuse-to-die-ko/

**Comment by iipeace** [comment]
저도 읽은 글이네요!  :)
현재 flask에서 Guider로부터 연결이 끊기면,
해당 소켓에 대한 getData()를 None으로 return만 하는데,
소켓 close 하고 이후 해당 socket에 api로 접근 시 error return 하도록 예외처리 추가해야겠네요!
