### ISSUE TITLE
Python 백엔드 개발시 이해해야할 자료 공유

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#89]
Python GIL
https://dgkim5360.tistory.com/entry/understanding-the-global-interpreter-lock-of-cpython

https://wangin9.tistory.com/m/entry/pythonthreadGIL

How Flask work
https://smirnov-am.github.io/background-jobs-with-flask/

**Comment by iipeace** [comment]
좋은 자료 같습니다,
특히 GIL은 파이썬에서 아주 중요한 내용이네요!

**Comment by yangsso** [comment]
추가로 virtualenv 활용해서 개발하면 좋습니다 :)

**Comment by yangsso** [comment]
init.py  이해하기
https://nesoy.github.io/articles/2018-07/Python-init-all

**Comment by iipeace** [comment]
__all__은 몰랐네요! :)

**Comment by yangsso** [comment]
Flask web framework 일반적인 구성들
nginx - gunicorn 다수 - 다수의 flask  
참고- https://winterj.me/flask-concurrency-test/
![image](https://user-images.githubusercontent.com/18661008/65775618-7d3eb780-e17b-11e9-9ab2-9fda82d09354.png)
