### ISSUE TITLE
Flask  기본 앱 구조 세팅 하기

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#90]
현재 __init__.py 만 존재하는 구조에서
model, biz 로직등을 따로 분리해서 담도록 구조화 세팅
필요한 구조만 빼와서 세팅 필요
(각 dir 안에는 __init__.py 추가 필요)

참고 
https://lepture.com/en/2018/structure-of-a-flask-project
https://libsora.so/posts/flask-project-structure/

```
함수 베이스로 아래처럼 놓을지
agent/
     __init__.py
    config.py
    app.py
    models/ 
        __init__.py
        users.py // 요건 나중을 위한 추가로~
        monitor.py ( 저장될 데이터 모델 네이밍 ...)
    routes/
       __init__.py  
       api.py
    templates/
       index.html(애초에 vue 쪽 봐버리면 날려도 됨)
    services/ 
       __init__.py
        monitor.py
    (controller)
       monitor_views.py( api request 받는 로직)
    
    tests/
      __init__.py (test 코드 넣을 부분)
```

app 베이스로 아래처럼 놓을지..
```
agent/
    __init__.py
    config.py
    app.py
    monitor/ (  뭔가 좋은거 없을까?)
        model.py
        views.py
        services.py
        routes.py
    tests/
        __init__.py
    templates/
       index.html
```

**Comment by sssunda** [comment]
작업예정!

**Comment by iipeace** [comment]
우선 실시간 정보(모니터링)를 다루려고 하지만,
이후 트레이싱, 제어, 유틸, 로깅 등 다양한 Guider의 다양한 기능을 다룰텐데,
함수 베이스 구조가 중복코드가 덜하고 공동작업하기 좋을까요?

**Comment by yangsso** [comment]
우선 app베이스로 가고 커몬을 따로 빼는것도 괜찮을 것 같아요  다은님 코멘트 남겨주세요 @sssunda

**Comment by sssunda** [comment]
http://exploreflask.com/en/latest/blueprints.html
참고해보니... app 베이스로 가는게 어떨까요???

**Comment by iipeace** [comment]
app base로 가시지요~!!

**Comment by iipeace** [comment]
PR #95가 merge 되었습니다.
#yangsso님, 확인 후 close 처리 해주세요 :)

**Comment by yangsso** [comment]
@sssunda 님 LGTM
