### ISSUE TITLE
flask mongo db config  세팅 추가 및, __init__ 파일과 연결 추가

### ISSUE THREAD

**Issue by yangsso** [iipeace/guider#91]
아래 세가지중에 자료 조사 후 선택한 이유와 함께 세팅해주시면 좋을거같아요~
Flask-PyMongo - https://flask-pymongo.readthedocs.io/en/latest/
Flask-MongoAlchemy - https://pythonhosted.org/Flask-MongoAlchemy/
Flask-MongoEngine - http://docs.mongoengine.org/projects/flask-mongoengine/en/latest/

- [ ] flask mongo db config 세팅 추가 (dir 위치는 추후 추가)
- [ ] init 파일 연결 추가
- [ ] 패키지 사용에 따른 requirements.py 추가

**Comment by Agrajak** [comment]
Flask-MongoAlchemy는 더 이상 Maintained되지 않는 것 같고 
Flask-MongoEngine으로 진행해보겠습니다.

굳이 Schema가 없는 NoSQL에서 모델을 정의하면서 코딩을 해야 하나 싶었는데 아무래도 코드 가독성은 MongoEngine이 훨씬 나은 것 같네요.

https://stackoverflow.com/questions/5712857/pymongo-vs-mongoengine-for-django
